src/components/InfoWindow.js
src/components/Marker.js

Use `T` instead of `React.PropTypes`

---

package.json

Move invariant to dependencies

---

src/lib/GoogleApi.js

https://github.com/fullstackreact/google-maps-react/issues/10

Fix for always setting null to window.google

---

src/components/Marker.js

Clear old marker when position change

Update marker position

---

src/components/Marker.js
src/index.js

New features: 
- support for custom icons for markers in Marker.js
- support for zoom changes through props on map in index.js

Custom marker icons and reaction to zoom changes

---

examples/Container.js
examples/components/withHeatMap.js
examples/index.js
src/components/HeatMap.js
src/index.js

I added heatmaps when using this in my project so I thought I would go ahead and add it here

Added HeatMap Component and Example

---

src/components/Marker.js

Without this I can't make simple marker example work.

Fix error:Cannot read property 'setMap' of undefined

---

src/index.js

Duplicate of https://github.com/fullstackreact/google-maps-react/pull/94, but not pulling master branch. #nooberrors...
Still solves https://github.com/fullstackreact/google-maps-react/issues/76

Fix undefined maps

---

src/components/Marker.js

Marker is not currently redrawn, if its icon changes.
I ran into this when attempting to change the color of an SVG path icon.

Also rerender marker, if its icon changes

---

.gitignore
dist/GoogleApiComponent.js
dist/components/HeatMap.js
dist/components/InfoWindow.js
dist/components/Marker.js
dist/index.js
dist/lib/GoogleApi.js
dist/lib/ScriptCache.js
dist/lib/String.js
dist/lib/cancelablePromise.js
src/index.js

Solves https://github.com/fullstackreact/google-maps-react/issues/76

Fix recentering when google.maps is not yet available

---

README.md

fix unclosed <Marker /> tag in documentation

close Marker in readme

---

src/GoogleApiComponent.js

Remove not used variable in `GoogleApiComponent`

remove not used variable

---

README.md

Added documentation to allow re-centering of map after initial render.

---

README.md
dist/components/Polyline.js
dist/index.js
src/components/Polyline.js
src/index.js

add the polyline component

---

dist/components/HeatMap.js
dist/components/InfoWindow.js
dist/components/Marker.js
dist/components/Polygon.js
dist/components/Polyline.js
examples/components/withPolylines.js
examples/index.js
src/components/HeatMap.js
src/components/InfoWindow.js
src/components/Marker.js
src/components/Polygon.js
src/components/Polyline.js

add more options to the components 

---

dist/components/Polygon.js
dist/components/Polyline.js
dist/lib/arePathsEqual.js
package-lock.json
src/__tests__/lib/arePathsEqual.spec.js
src/components/Polygon.js
src/components/Polyline.js
src/lib/arePathsEqual.js

Polyline and Polygon implementations have a bug in responding to path prop updates (#189). This fixes it.

Update Polyline and Polygon on path change

---

src/index.js

check for bounds null on componentDidUpdate #235

---

src/GoogleApiComponent.js

Pass region option from GoogleApiComponent to GoogleApi

Pass region option from GoogleApiComponent

---

src/components/HeatMap.js

I am using this library in one of my projects and I wanted to give weighted heatmap points so I changed it a little bit and it worked.
This would be a nice feature to add.

added functionality for weighted positions in heatmap component

---

index.d.ts
package-lock.json
package.json

Howdy!
Love this library, it was a great help to us getting started on using Google Maps in our react app.
In the process of building out our app, we wrote Typescript definitions for the parts that we used, primarily `Map`, `Marker`, and `InfoWindow`.  Hope these are helpful to someone else!

Add Typescript definitions

---

dist/index.js

Changed the `mapOptions` (lines 270-271) to allow the user to specify their own cursor, and additionally added them to `propTypes` (lines 418-419).

Optional cursor props to change default cursors

---

index.d.ts

Some things were missing from IMapProps.

Add style, containerStyle and center to IMapProps

---

examples/components/withRectangle.js
examples/index.js
src/components/Rectangle.js
src/index.js
src/lib/areBoundsEqual.js

Fix: #403
Added Rectangle Component for React Google Maps
Below is the demo:-
**Completed?:** (Yes)

Complete Issue#403 - Add rectangle component

---

README.md

Adding the container style prop to the readme instructions.
Tried to copy style of previous style section.

Adding detail for container style in the readme

---

dist/GoogleApiComponent.js
dist/index.js

Sorry the last related PR will work, but had an older version of the dist file. Adding a PR to update that.
https://github.com/fullstackreact/google-maps-react/pull/412

Convert string refs to create refs: dist files

---

src/lib/ScriptCache.js

Fix uncatched exception when loading google maps api.

---

index.d.ts

update props to match the component

update InfoWindow typescript props interface

---

src/GoogleApiComponent.js

This fixes the following open issue https://github.com/fullstackreact/google-maps-react/issues/298

wrapper map div accepts className and style
