fullstackreact/google-maps-react

src/GoogleApiComponent.js
src/lib/GoogleApi.js

Specifying a retired version, such as `v=3.24`, will return the current frozen version and show a warning. Specifying `v=3` will return the current release version instead. More info [here](https://developers.google.com/maps/documentation/javascript/versions).

Use Google Maps API release version

---

src/index.js

This prop allows the gestureHandling option to be modified on the Google Map instance. All tests pass.

(fix) Add gestureHandling prop to Map component (Closes #46)

---

README.md
examples/Container.js
package.json
src/GoogleApiComponent.js
src/components/HeatMap.js
src/components/InfoWindow.js
src/components/Marker.js
src/index.js

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html
"The biggest change is that we've extracted React.PropTypes and React.createClass into their own packages. Both are still accessible via the main React object, but using either will log a one-time deprecation warning to the console when in development mode."

Moved to prop-types package for compatibility with React 15.5

---

README.md

onReady is called before google object is passed to the component as props, I think that is why you've passed mapProps and map as parameters explicitly

changed this.props to mapProps

---

README.md
examples/components/withMarkers.js
src/components/Marker.js

Marker component now allows to define also title prop which will appear as a tooltip.

Feature marker title

---

src/index.js

This fixes an error I'm getting when adding children to the Map conditionally. If the Map children array contains null or undefined elements, the cloneElement function fails. Checking before cloning solves it.
Full story:
I have a Marker and a custom Circle component I'm adding to the map, conditionally. Something like
```
render: function() {
let marker = null;
if (this.state.lat && this.state.lng) {
marker = (
<Marker name={'marker'}
position={{lat: this.state.currentLat, lng: this.state.currentLng}} />);
}
let circle = null;
if (this.state.lat && this.state.lng && this.props.radius) {
circle = (
<Circle [...] />);
}
return (
<div className="some-class">
<Map ref='map' [...]>
{circle}
{marker}
</Map>
);
}
```
However, if one of these variables (marker and circle) is null, they show up …

Check if child is null before cloning

---

src/GoogleApiComponent.js
src/lib/GoogleApi.js

I live in Quebec so, most of our websites are bilingual. With this PR, we can now specify the language in which we want to load the Google API library.
```js
export default GoogleApiWrapper({
apiKey: 'API_KEY',
language: 'fr'
})(Container);
```

Add possibility to provide a language when loading Google API library

---

README.md

When I initially tried to use this library I ran into a number of different problems. Though after digging through the code and number of the posted issues, I was able to utilize the tool with a few workarounds, my experience led me to realize a number basic improvements that could be added to the readme to help new-users, especially those (like me) who are newer to react. With this update I hope to address parts of a few issues raised by other users, including: #59, #58, #44, & #25. 
1. First, I added what I consider a better code sample and moved the notation about lazy-loading to the top of the readme. The sample usage now shows a fully fleshed out example of the proper code that demonstrates importing components, using a container class, and connecting it to the lazy-loading at the …

Update readme to help beginners get started

---

README.md
examples/components/clickableMarkers.js
src/components/InfoWindow.js

Hi, according to [google maps](https://developers.google.com/maps/documentation/javascript/infowindows) documentation, it should be possible to set the position of the InfoWindow component without using a marker.

Feature InfoWindow position

---

src/components/Marker.js
src/index.js

Extended the mouse events that can be handled in the ``Marker`` component, as described here: https://developers.google.com/maps/documentation/javascript/events

Extend marker mouse events

---

src/index.js

Currently null children crashes with
```
ReactElement.js:271 Uncaught TypeError: Cannot read property 'props' of null
at Object.ReactElement.cloneElement (ReactElement.js:271)
at Object.cloneElement (ReactElementValidator.js:242)
at index.js:315
at mapSingleChildIntoContext (ReactChildren.js:107)
at traverseAllChildrenImpl (traverseAllChildren.js:77)
at traverseAllChildrenImpl (traverseAllChildren.js:93)
at traverseAllChildren (traverseAllChildren.js:172)
at mapIntoWithKeyPrefixInternal (ReactChildren.js:127)
at Object.mapChildren [as map] (ReactChildren.js:149)
```

Fix render crashing with null children

---

dist/lib/GoogleApi.js

Fixes issue: https://github.com/fullstackreact/google-maps-react/issues/64
Relates to: https://github.com/fullstackreact/google-maps-react/issues/7  (closed, PR merged)
Description: 
For isomorphic applications trying to access GoogleApiWrapper the window object is not defined (see fixes issue link above). So an error is being formed. This PR addresses that error. 
There was a similar error in ScriptCache.js that was recently merged (see relates to link above).

Fixed Window Error for Isomorphic Applications Accessing GoogleApiWrapper

---

dist/components/Marker.js

1) Allow user to pass 'zIndex' and 'optimized' props to marker class. Setting the 'optimized' property to 'false' seems to help the user determine which marker displays on top using the zIndex property. See: https://stackoverflow.com/questions/11845916/google-maps-marker-zindex-doesnt-work-for-two-icon-types-symbol-and-string

Add zIndex support for marker

---

dist/components/Polygon.js
src/components/Polygon.js

Issue: https://github.com/fullstackreact/google-maps-react/issues/114
Fix: call to renderPolygon() was inside a conditional that was impossible to meet.

Fixing issue preventing polygon from rendering

---

src/index.js

Revert change from PR #126 to fix option minZoom from props
https://github.com/fullstackreact/google-maps-react/commit/f626c208c3a8010cf547b3643c6557cde62ee588#diff-1fdf421c05c1140f6d71444ea2b27638R145

Revert change from PR #126 to fix (again) #110

---

src/lib/GoogleApi.js

Enable searching in a specific region by passing the region to the API. 
Currently `region` is defaulted as `null`.
Something like this:
```
export default GoogleApiWrapper({
apiKey: MY_API_KEY,
region: 'NZ'
})(MY_COMPONENT)
```

Accept region as an optional param

---

README.md
dist/index.js
dist/lib/GoogleApi.js
src/index.js

Fixes #183 
This allows the map to be centered to fit a polyline, by passing a bounds prop to the map.
I tested locally building on top of pull request #203 so probably merge that one first. 
The commit "Accept region as option param" got caught up in here because the dist was not committed.

Expose fitBounds() on Map component

---

dist/lib/GoogleApi.js
dist/lib/ScriptCache.js
src/lib/GoogleApi.js
src/lib/ScriptCache.js

We're trying to use this module with Gatsby and found that it fails to build because it sometimes assumes the existence of both `document` and `window`.
These two fixes make it so it works in Gatsby. If you have any questions or there's a better way to do this, just let me know. Thanks!

Server side rendering fixes for Gatsby.

---

src/GoogleApiComponent.js

Adds 'client' argument into 'ScriptCache' call. This is useful to load Google Maps API when you only have clientID  (Google's Premium Plan users).

Add 'client' argument (Update GoogleApiComponent.js)

---

README.md

In documentation there is prop named paths in polyline component, but it needs to be path.

polyline documentation fix [README.md]

---

README.md

Should be path instead of paths. Refer to issue #225

Polyline example has typo

---

dist/lib/String.js
src/lib/String.js

Quick fix for prop event names with underscores
i.e. `bounds changed` becomes `Bounds_changed` with current camelize, so prop name has to be `onBounds_changed`.
This fixes it so that the prop name will be `onBoundsChanged`

Underscore event props

---

src/lib/GoogleApi.js

This allows you to set an onError callback function in case the map doesn't load correctly.

Add an error call back param

---

README.md

The link to the example on README is missing the `http://` part and because of that, it leads to the wrong destination.
correct destination: http://fullstackreact.github.io/basic
wrong destination: https://github.com/fullstackreact/google-maps-react/blob/master/fullstackreact.github.io/google-maps-react

Fixing link to example on README

---

src/components/Marker.js

Let's say you want to a simple map with 1 marker and you want to have an InfoWindow open when the component renders. For example, you want a location and you want to show some details about the location in an InfoWindow. InfoWindow requires either a position or a marker, but if you use the position, it will be laid on top of the marker. 
This change allows the InfoWindow to be passed as a child inside of the Marker and passes on the Marker's marker, google and map to the child. Example:
```
<Marker
title="Location"
id={1}
position={markerCenter}
draggable={true}
onDragend={this.moveMarker.bind(this)}
>
<InfoWindow
visible={showInfoWindow}
style={styles.infoWindow}
>
<div className={classes.infoWindow}>
<p>Click on the map or drag the marker to select location where the incident …
```

Adding support for InfoWindow as a prop child of Marker

---

package.json

We have the `index.d.ts` file in this repo, but without including it in the `files` array it is not included in the distributed package. If this PR is merged it means typescript users will not need to do `npm install @types/google-maps-react`.

include types in files

---

dist/index.js
src/GoogleApiComponent.js
src/index.js

Converting string refs to callback refs because Preact 10 deprecated string refs making it incompatible with google-maps-react. React plans to deprecate string refs as well, so it would be needed in the long run.
Preact 10 deprecated string refs:
https://github.com/preactjs/preact/issues/2172
React planning to deprecate string refs: Look to the string refs section.
https://reactjs.org/docs/refs-and-the-dom.html

Convert string refs to create refs

---

src/components/Marker.js

Fix: #406 
Fix Marker Component
Below is the screenshot:-
**Completed?:** (Yes)

Fix Marker Component

---

src/GoogleApiComponent.js

Addresses the new warning returned by the new react version:
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
Please update …

Fix deprecation message for componentWillReceiveProps 

---

README.md

The google api events with underscored are not camelized properly. So until this is fixed these are the right names for the events.

Use right event names

---

src/GoogleApiComponent.js

Adds component will unmount to `GoogleApiComponent` - closes #248

Fix: Unregister load handler on unmount of Google API component

---

package.json

this allows for more advanced DCE of components that aren't being used, e.g. if you don't use `InfoWindow` no need to include it in the bundle
https://github.com/webpack/webpack/tree/master/examples/side-effects

mark package as tree shakeable

---

dist/lib/String.js
src/lib/String.js

This was already solved in https://github.com/fullstackreact/google-maps-react/pull/278
Somehow it was removed by one of the commits in https://github.com/fullstackreact/google-maps-react/pull/280, even though the diff does not show it as a change.
This is to get it back in so that the already solved problem of multi-word events (i.e. `bounds_changed`) are properly mapped to multi-word prop names. (i.e. `onBoundsChanged` instead of `onBounds_changed`

Handle underscore events

---

index.d.ts

Here is an example from the repo.
Since `onDragend` is not defined, this example will cause a compile error in TS.

Add onDragend to IMarkerProps
